female(maggie).
female(lisa).
female(marge).
female(patty).
female(selma).
female(jackie).

male(bart).
male(homer).
male(herb).
male(burns).
male(smithers).
male(tod).
male(rod).
male(ned).

parent(bart,homer).
parent(bart,marge).
parent(lisa,homer).
parent(lisa,marge).
parent(maggie,homer).
parent(maggie,marge).
parent(homer,abraham).
parent(herb,abraham).
parent(tod,ned).
parent(rod,ned).
parent(marge,jackie).
parent(patty,jackie).
parent(selma,jackie).

grandfather(bart,abraham).
grandfather(maggie,abraham).
grandfather(lisa,abraham).

grandmother(maggie,jackie).
grandmother(lisa,jackie).
grandmother(bart,jackie).

ancestor(abraham,bart).
ancestor(abraham,maggie).
ancestor(abraham,lisa).
ancestor(jackie,maggie).
ancestor(jackie,lisa).
ancestor(jackie,bart).


granddaughter(jackie, maggie).
granddaughter(jackie, lisa).

aunt(lisa,patty).
aunt(maggie,patty).

uncle(maggie,selma).
uncle(lisa,selma).
uncle(bart,herb).

brother(lisa,bart).
brother(rod,tod).
brother(tod,rod).
brother(marge,selma).
brother(patther,selma).
brother(herb,homer).
brother(homer,herb).
brother(maggie,bart).

sister(bart,lisa).
sister(bart,marge).
sister(selma,marge).
sister(selma,patty).
sister(maggie,lisa).
sister(lisa,maggie).
sister(marge,patty).
sister(patty,marge).

relative(tod,ned).
relative(rod,ned).
relative(ned,tod).
relative(ned,rod).
relative(rod,tod).
relative(tod,rod).
relative(patty,marge).
relative(jackie,marge).
relative(selma,marge).
relative(abraham,marge).
relative(herb,marge).
relative(homer,marge).
relative(maggie,marge).
relative(lisa,marge).
relative(bart,marge).
relative(jackie,patty).
relative(selma,patty).
relative(abraham,patty).
relative(herb,patty).
relative(homer,patty).
relative(maggie,patty).
relative(lisa,patty).
relative(bart,patty).
relative(marge,patty).
relative(marge,jackie).
relative(patty,jackie).
relative(selma,jackie).
relative(abraham,jackie).
relative(herb,jackie).
relative(homer,jackie).
relative(maggie,jackie).
relative(lisa,jackie).
relative(bart,jackie).
relative(marge,selma).
relative(patty,selma).
relative(jackie,selma).
relative(abraham,selma).
relative(herb,selma).
relative(homer,selma).
relative(maggie,selma).
relative(lisa,selma).
relative(bart,selma).
relative(marge,abraham).
relative(patty,abraham).
relative(jackie,abraham).
relative(selma,abraham).
relative(herb,abraham).
relative(homer,abraham).
relative(maggie,abraham).
relative(lisa,abraham).
relative(bart,abraham).
relative(marge,herb).
relative(patty,herb).
relative(jackie,herb).
relative(selma,herb).
relative(abraham,herb).
relative(homer,herb).
relative(maggie,herb).
relative(lisa,herb).
relative(bart,herb).
relative(marge,homer).
relative(patty,homer).
relative(jackie,homer).
relative(selma,homer).
relative(abraham,homer).
relative(herb,homer).
relative(maggie,homer).
relative(lisa,homer).
relative(bart,homer).
relative(marge,maggie).
relative(patty,maggie).
relative(jackie,maggie).
relative(selma,maggie).
relative(abraham,maggie).
relative(herb,maggie).
relative(homer,maggie).
relative(lisa,maggie).
relative(bart,maggie).
relative(marge,lisa).
relative(patty,lisa).
relative(jackie,lisa).
relative(selma,lisa).
relative(abraham,lisa).
relative(herb,lisa).
relative(homer,maggie).
relative(maggie,lisa).
relative(lisa,lisa).
relative(bart,lisa).
relative(marge,bart).
relative(patty,bart).
relative(jackie,bart).
relative(selma,bart).
relative(abraham,bart).
relative(herb,bart).
relative(homer,maggie).
relative(maggie,bart).
relative(lisa,bart).


unrelated(ned,bart).
unrelated(ned,lisa).
unrelated(ned,maggie).
unrelated(ned,homer).
unrelated(ned,herb).
unrelated(ned,abraham).
unrelated(ned,marge).
unrelated(ned,patty).
unrelated(ned,jackie).
unrelated(ned,selma).
unrelated(rod,bart).
unrelated(rod,lisa).
unrelated(rod,maggie).
unrelated(rod,homer).
unrelated(rod,herb).
unrelated(rod,abraham).
unrelated(rod,marge).
unrelated(rod,patty).
unrelated(rod,jackie).
unrelated(rod,selma).
unrelated(tod,bart).
unrelated(tod,lisa).
unrelated(tod,maggie).
unrelated(tod,homer).
unrelated(tod,herb).
unrelated(tod,abraham).
unrelated(tod,marge).
unrelated(tod,patty).
unrelated(tod,jackie).
unrelated(tod,selma).
unrelated(bart,burns).
unrelated(lisa,burns).
unrelated(maggie,burns).
unrelated(homer,burns).
unrelated(herb,burns).
unrelated(tod,burns).
unrelated(rod,burns).
unrelated(ned,burns).
unrelated(abraham,burns).
unrelated(marge,burns).
unrelated(patty,burns).
unrelated(jackie,burns).
unrelated(selma,burns).
unrelated(marge,smithers).
unrelated(patty,smithers).
unrelated(jackie,smithers).
unrelated(selma,smithers).
unrelated(abraham,smithers).
unrelated(tod,smithers).
unrelated(ned,smithers).
unrelated(rod,smithers).
unrelated(herb,smithers).
unrelated(homer,smithers).
unrelated(maggie,smithers).
unrelated(lisa,smithers).
unrelated(bart,smithers).
unrelated(marge,ned).
unrelated(patty,ned).
unrelated(jackie,ned).
unrelated(selma,ned).
unrelated(abraham,ned).
unrelated(herb,ned).
unrelated(homer,ned).
unrelated(maggie,ned).
unrelated(lisa,ned).
unrelated(bart,ned).
unrelated(marge,rod).
unrelated(patty,rod).
unrelated(jackie,rod).
unrelated(selma,rod).
unrelated(abraham,rod).
unrelated(herb,rod).
unrelated(homer,rod).
unrelated(maggie,rod).
unrelated(lisa,rod).
unrelated(bart,rod).
unrelated(marge,tod).
unrelated(patty,tod).
unrelated(jackie,tod).
unrelated(selma,tod).
unrelated(abraham,tod).
unrelated(herb,tod).
unrelated(homer,tod).
unrelated(maggie,tod).
unrelated(lisa,tod).
unrelated(bart,tod).
unrelated(burns,bart).
unrelated(burns,lisa).
unrelated(burns,maggie).
unrelated(burns,homer).
unrelated(burns,herb).
unrelated(burns,tod).
unrelated(burns,rod).
unrelated(burns,ned).
unrelated(burns,abraham).
unrelated(burns,marge).
unrelated(burns,patty).
unrelated(burns,jackie).
unrelated(burns,selma).
unrelated(smithers,bart).
unrelated(smithers,lisa).
unrelated(smithers,maggie).
unrelated(smithers,homer).
unrelated(smithers,herb).
unrelated(smithers,tod).
unrelated(smithers,rod).
unrelated(smithers,ned).
unrelated(smithers,abraham).
unrelated(smithers,marge).
unrelated(smithers,patty).
unrelated(smithers,jackie).
unrelated(smithers,selma).